# Generated by Django 4.2.11 on 2024-08-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_app', '0002_author_book_bookauthor_delete_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
